// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[slug]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[slug]")>;
    },
    {
      path: "/about";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/about")>;
      $$route?: undefined;
    },
    {
      path: "/agenda";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/agenda")>;
      $$route?: undefined;
    },
    {
      path: "/confirm-password-reset";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/confirm-password-reset")>;
      $$route?: undefined;
    },
    {
      path: "/confirm-verification";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/confirm-verification")>;
      $$route?: undefined;
    },
    {
      path: "/faq";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/faq")>;
      $$route?: undefined;
    },
    {
      path: "/forgot-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/forgot-password")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/mcp";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/mcp")>;
      $$route?: undefined;
    },
    {
      path: "/ops-board";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/ops-board")>;
      $$route?: undefined;
    },
    {
      path: "/press-kit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/press-kit")>;
      $$route?: undefined;
    },
    {
      path: "/register";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/register")>;
      $$route?: undefined;
    },
    {
      path: "/speaker-guide";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speaker-guide")>;
      $$route?: undefined;
    },
    {
      path: "/sponsors";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/sponsors")>;
      $$route?: undefined;
    },
    {
      path: "/tickets";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/tickets")>;
      $$route?: undefined;
    },
    {
      path: "/timeline";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/timeline")>;
      $$route?: undefined;
    },
    {
      path: "/trip-cost";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/trip-cost")>;
      $$route?: undefined;
    },
    {
      path: "/admin/agenda";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/agenda")>;
      $$route?: undefined;
    },
    {
      path: "/admin/gamification";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/gamification")>;
      $$route?: undefined;
    },
    {
      path: "/admin/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
      $$route?: undefined;
    },
    {
      path: "/admin/mcp";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/mcp")>;
      $$route?: undefined;
    },
    {
      path: "/admin/partners";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/partners")>;
      $$route?: undefined;
    },
    {
      path: "/admin/proposals";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/proposals")>;
      $$route?: undefined;
    },
    {
      path: "/admin/sessions";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/sessions")>;
      $$route?: undefined;
    },
    {
      path: "/admin/speakers";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/speakers")>;
      $$route?: undefined;
    },
    {
      path: "/admin/tickets";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/tickets")>;
      $$route?: undefined;
    },
    {
      path: "/admin/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/users")>;
      $$route?: undefined;
    },
    {
      path: "/admin/weights";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/weights")>;
      $$route?: undefined;
    },
    {
      path: "/api/image";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/image")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/image")>;
      $$route?: undefined;
    },
    {
      path: "/api/mcp";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/mcp")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/mcp")>;
      $DELETE: FileRouteLazyRef<typeof import("./src/routes/api/mcp")>;
      $OPTIONS: FileRouteLazyRef<typeof import("./src/routes/api/mcp")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/mcp")>;
      $$route?: undefined;
    },
    {
      path: "/api/nr-metadata-sse";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/nr-metadata-sse")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/nr-metadata-sse")>;
      $$route?: undefined;
    },
    {
      path: "/api/nr-metadata";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/nr-metadata")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/nr-metadata")>;
      $$route?: undefined;
    },
    {
      path: "/api/og";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/og")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/og")>;
      $$route?: undefined;
    },
    {
      path: "/blog/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog/[slug]")>;
      $$route?: undefined;
    },
    {
      path: "/blog/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog/index")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/01-intro";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/01-intro")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/02-personal";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/02-personal")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/03-proposal";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/03-proposal")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/04-experience";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/04-experience")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/05-expenses";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/05-expenses")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/06-confirmation";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/06-confirmation")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/closed";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/closed")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/index")>;
      $$route?: undefined;
    },
    {
      path: "/cfp/my-submissions";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/my-submissions")>;
      $$route?: undefined;
    },
    {
      path: "/missions/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/missions/index")>;
      $$route?: undefined;
    },
    {
      path: "/missions/redeem";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/missions/redeem")>;
      $$route?: undefined;
    },
    {
      path: "/prototype/press-kit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/prototype/press-kit")>;
      $$route?: undefined;
    },
    {
      path: "/qr/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/qr/[slug]")>;
      $$route?: undefined;
    },
    {
      path: "/reviewer/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/[id]")>;
      $$route?: undefined;
    },
    {
      path: "/reviewer/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/index")>;
      $$route?: undefined;
    },
    {
      path: "/reviewer/leaderboard";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/leaderboard")>;
      $$route?: undefined;
    },
    {
      path: "/reviewer/weights";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/weights")>;
      $$route?: undefined;
    },
    {
      path: "/sessions/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/sessions/[slug]")>;
      $$route?: undefined;
    },
    {
      path: "/sessions/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/sessions/index")>;
      $$route?: undefined;
    },
    {
      path: "/speakers/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speakers/index")>;
      $$route?: undefined;
    },
    {
      path: "/user/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/index")>;
      $$route?: undefined;
    },
    {
      path: "/user/profile";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/profile")>;
      $$route?: undefined;
    },
    {
      path: "/api/mcp/public";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $DELETE: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $OPTIONS: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $$route?: undefined;
    },
    {
      path: "/speakers/:slug/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speakers/[slug]/index")>;
      $$route?: undefined;
    },
    {
      path: "/speakers/:slug/promo";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speakers/[slug]/promo")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/faq";
      id: "/faq";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/faq")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/mcp";
      id: "/mcp";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/mcp")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/cfp/";
      id: "/cfp/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/:slug";
      id: "/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[slug]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[slug]")>;
      children?: undefined;
    },
    {
      path: "/about";
      id: "/about";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/about")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/blog/";
      id: "/blog/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/user/";
      id: "/user/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/agenda";
      id: "/agenda";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/agenda")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/";
      id: "/admin/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/tickets";
      id: "/tickets";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/tickets")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/register";
      id: "/register";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/register")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/sponsors";
      id: "/sponsors";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/sponsors")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/timeline";
      id: "/timeline";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/timeline")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/qr/:slug";
      id: "/qr/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/qr/[slug]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/ops-board";
      id: "/ops-board";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/ops-board")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/press-kit";
      id: "/press-kit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/press-kit")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/trip-cost";
      id: "/trip-cost";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/trip-cost")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/mcp";
      id: "/admin/mcp";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/mcp")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/missions/";
      id: "/missions/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/missions/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/reviewer/";
      id: "/reviewer/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/sessions/";
      id: "/sessions/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/sessions/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/speakers/";
      id: "/speakers/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speakers/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/blog/:slug";
      id: "/blog/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/blog/[slug]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/closed";
      id: "/cfp/closed";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/closed")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/users";
      id: "/admin/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/users")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/agenda";
      id: "/admin/agenda";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/agenda")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/01-intro";
      id: "/cfp/01-intro";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/01-intro")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/reviewer/:id";
      id: "/reviewer/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/[id]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/user/profile";
      id: "/user/profile";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/profile")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/speaker-guide";
      id: "/speaker-guide";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speaker-guide")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/tickets";
      id: "/admin/tickets";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/tickets")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/weights";
      id: "/admin/weights";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/weights")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/partners";
      id: "/admin/partners";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/partners")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/sessions";
      id: "/admin/sessions";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/sessions")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/speakers";
      id: "/admin/speakers";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/speakers")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/sessions/:slug";
      id: "/sessions/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/sessions/[slug]")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/forgot-password";
      id: "/forgot-password";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/forgot-password")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/proposals";
      id: "/admin/proposals";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/proposals")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/02-personal";
      id: "/cfp/02-personal";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/02-personal")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/03-proposal";
      id: "/cfp/03-proposal";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/03-proposal")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/05-expenses";
      id: "/cfp/05-expenses";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/05-expenses")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/missions/redeem";
      id: "/missions/redeem";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/missions/redeem")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/speakers/:slug/";
      id: "/speakers/:slug/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speakers/[slug]/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/reviewer/weights";
      id: "/reviewer/weights";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/weights")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/04-experience";
      id: "/cfp/04-experience";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/04-experience")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/admin/gamification";
      id: "/admin/gamification";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/admin/gamification")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/my-submissions";
      id: "/cfp/my-submissions";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/my-submissions")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/cfp/06-confirmation";
      id: "/cfp/06-confirmation";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/cfp/06-confirmation")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/prototype/press-kit";
      id: "/prototype/press-kit";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/prototype/press-kit")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/confirm-verification";
      id: "/confirm-verification";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/confirm-verification")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/reviewer/leaderboard";
      id: "/reviewer/leaderboard";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/reviewer/leaderboard")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/speakers/:slug/promo";
      id: "/speakers/:slug/promo";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/speakers/[slug]/promo")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/confirm-password-reset";
      id: "/confirm-password-reset";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/confirm-password-reset")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
