allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  sqlite3: true
minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.11.20
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - node-sqlite3
  - sharp
  - sqlite3
overrides:
  '@babel/core': 7.29.6
  '@mapbox/node-pre-gyp>tar': 7.5.16
  'brace-expansion@>=5.0.0 <5.0.6': 5.0.6
  prosemirror-model: 1.25.11
  vite@*: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
