// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[slug]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[slug]")>;
    },
    {
      path: "/forgot-password";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/forgot-password")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/forgot-password")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/mcp";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/mcp")>;
      $$route?: undefined;
    },
    {
      path: "/readyz";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/readyz")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/readyz")>;
      $$route?: undefined;
    },
    {
      path: "/register";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/register")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/register")>;
      $$route?: undefined;
    },
    {
      path: "/api/image";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/image")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/image")>;
      $$route?: undefined;
    },
    {
      path: "/api/og";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/og")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/og")>;
      $$route?: undefined;
    },
    {
      path: "/auth/callback";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/auth/callback")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/auth/callback")>;
      $$route?: undefined;
    },
    {
      path: "/auth/login";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/auth/login")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/auth/login")>;
      $$route?: undefined;
    },
    {
      path: "/auth/logout";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/auth/logout")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/auth/logout")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/auth/logout")>;
      $$route?: undefined;
    },
    {
      path: "/media/:assetId";
      page: false;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/media/[assetId]")>;
      $GET: FileRouteLazyRef<typeof import("./src/routes/media/[assetId]")>;
      $$route?: undefined;
    },
    {
      path: "/user/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/index")>;
      $$route?: undefined;
    },
    {
      path: "/user/profile";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/profile")>;
      $$route?: undefined;
    },
    {
      path: "/api/mcp/public";
      page: false;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $DELETE: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $OPTIONS: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/mcp/public")>;
      $$route?: undefined;
    },
    {
      path: "/api/public/v1/*path";
      page: false;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $PUT: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $DELETE: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $PATCH: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $OPTIONS: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/[...path]")>;
      $$route?: undefined;
    },
    {
      path: "/api/public/v1/";
      page: false;
      $HEAD: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $GET: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $POST: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $PUT: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $DELETE: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $PATCH: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $OPTIONS: FileRouteLazyRef<typeof import("./src/routes/api/public/v1/index")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/mcp";
      id: "/mcp";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/mcp")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/:slug";
      id: "/:slug";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[slug]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[slug]")>;
      children?: undefined;
    },
    {
      path: "/user/";
      id: "/user/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/user/profile";
      id: "/user/profile";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/user/profile")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
