// This file is generated by Velite

export { default as conferenceGuide } from './conferenceGuide.json' with { type: 'json' }
export { default as speakerGuide } from './speakerGuide.json' with { type: 'json' }
export { default as pages } from './pages.json' with { type: 'json' }
export { default as posts } from './posts.json' with { type: 'json' }