import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";

const require = createRequire(import.meta.url);
const manifestPath = resolve("scripts/icon-manifest.json");
const outputPath = resolve("src/generated/icons.ts");

const iconNames = JSON.parse(await readFile(manifestPath, "utf8"));
if (!Array.isArray(iconNames) || iconNames.some((name) => typeof name !== "string")) {
  throw new Error("scripts/icon-manifest.json must contain an array of icon names.");
}

const uniqueNames = [...new Set(iconNames)];
if (uniqueNames.length !== iconNames.length) {
  throw new Error("scripts/icon-manifest.json contains duplicate icon names.");
}

const collections = new Map();
for (const fullName of uniqueNames) {
  const separator = fullName.indexOf(":");
  if (separator < 1 || separator === fullName.length - 1) {
    throw new Error(`Invalid icon name: ${fullName}`);
  }

  const prefix = fullName.slice(0, separator);
  if (!collections.has(prefix)) {
    const packagePath = require.resolve(`@iconify-json/${prefix}/icons.json`);
    collections.set(prefix, JSON.parse(await readFile(packagePath, "utf8")));
  }
}

function combineFlip(parentValue, ownValue) {
  return Boolean(parentValue) !== Boolean(ownValue);
}

function resolveIcon(prefix, name, seen = new Set()) {
  const collection = collections.get(prefix);
  const key = `${prefix}:${name}`;
  if (seen.has(key)) throw new Error(`Circular Iconify alias: ${key}`);
  seen.add(key);

  const icon = collection.icons?.[name];
  if (icon) {
    return {
      body: icon.body,
      left: icon.left ?? collection.left ?? 0,
      top: icon.top ?? collection.top ?? 0,
      width: icon.width ?? collection.width ?? 16,
      height: icon.height ?? collection.height ?? 16,
      ...(icon.rotate ? { rotate: icon.rotate } : {}),
      ...(icon.hFlip ? { hFlip: true } : {}),
      ...(icon.vFlip ? { vFlip: true } : {}),
    };
  }

  const alias = collection.aliases?.[name];
  if (!alias) throw new Error(`Icon not found in @iconify-json/${prefix}: ${name}`);

  const parent = resolveIcon(prefix, alias.parent, seen);
  const rotate = ((parent.rotate ?? 0) + (alias.rotate ?? 0)) % 4;
  return {
    ...parent,
    ...(alias.left === undefined ? {} : { left: alias.left }),
    ...(alias.top === undefined ? {} : { top: alias.top }),
    ...(alias.width === undefined ? {} : { width: alias.width }),
    ...(alias.height === undefined ? {} : { height: alias.height }),
    ...(rotate ? { rotate } : {}),
    ...(combineFlip(parent.hFlip, alias.hFlip) ? { hFlip: true } : {}),
    ...(combineFlip(parent.vFlip, alias.vFlip) ? { vFlip: true } : {}),
  };
}

const icons = Object.fromEntries(
  uniqueNames.sort().map((fullName) => {
    const separator = fullName.indexOf(":");
    const prefix = fullName.slice(0, separator);
    const name = fullName.slice(separator + 1);
    return [fullName, resolveIcon(prefix, name)];
  }),
);

await mkdir(resolve("src/generated"), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/generate-icons.mjs. Do not edit by hand.\n\nexport interface LocalIconData {\n  body: string;\n  left: number;\n  top: number;\n  width: number;\n  height: number;\n  rotate?: number;\n  hFlip?: boolean;\n  vFlip?: boolean;\n}\n\nexport const localIcons = ${JSON.stringify(icons, null, 2)} as const satisfies Record<string, LocalIconData>;\n\nexport type LocalIconName = keyof typeof localIcons;\n`,
);

console.log(`Generated ${uniqueNames.length} local icons in ${outputPath}`);
